services:
  workspace:
    image: mcr.microsoft.com/devcontainers/rust:1-bookworm
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - ./workspace/root/.bash_history:/root/.bash_history:cached
      - ./workspace/root/.bashrc:/root/.bashrc:cached
      - workspace-cargo:/workspace/.cargo
      - workspace-target:/workspace/target
    environment:
      CARGO_HOME: /workspace/.cargo
    networks:
      net:

volumes:
  workspace-cargo:
  workspace-target:

networks:
  net:
