services:
  workspace:
    image: mcr.microsoft.com/devcontainers/rust:1-bookworm
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - ./workspace/root/.bash_history:/root/.bash_history:cached
      - ./workspace/root/.bashrc:/root/.bashrc:cached
    networks:
      net:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      net:

networks:
  net:
